# docker-compose.yml

version: "3.9"

services:
  db:
    image: postgres:15.1-alpine
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
     - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  bot:
      container_name: bot
      build:
        context: .
        dockerfile: Dockerfile
      restart: on-failure
      env_file:
        - .env
      environment:
        POSTGRES_HOST: db
      links:
        - db
      depends_on:
        - db

networks:
  default:
      name: lan
